FROM arm32v6/alpine

RUN apk add vips-dev fftw-dev build-base --update-cache \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/testing/ \
    --repository https://alpine.global.ssl.fastly.net/alpine/edge/main

RUN apk add --update \
    --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
    vips-tools \
    nodejs=10.14.2-r0
    nodejs-npm=10.14.2-r0 \
    python \
    python-dev \
    py-pip \
    build-base \
    vips \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

RUN npm install

EXPOSE 3000
CMD [ "node", "app.js" ]